name = "NStrings"
uuid = "4db0a0c5-418a-4e1d-8806-cb305fe13294"
authors = ["Mark Kittisopikul <markkitt@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"

[compat]
Compat = "4"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
